version: '3'

services:
  test:
    image: native-test
    command: node index.js
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - linux/amd64
    working_dir: /app
    volumes:
      - .:/app
